export const BODY_PARTS: any[] = [
  {
    key: '1',
    name: 'Chest',
  },
  {
    key: '2',
    name: 'Back',
  },
  {
    key: '3',
    name: 'Biceps',
  },
  {
    key: '4',
    name: 'Triceps',
  },
  {
    key: '5',
    name: 'Glutes',
  },
  {
    key: '6',
    name: 'Hamstrings',
  },
  {
    key: '7',
    name: 'Quads',
  },
  {
    key: '8',
    name: 'Calfs',
  },
  {
    key: '9',
    name: 'Shoulders',
  },
  {
    key: '10',
    name: 'Core',
  },
];

export const EXERCISES = {
  pushup: 'Pushups',
  chestDips: 'Chest Dips',
  inclineBench: 'Incline Bench Press',
  benchPress: 'Bench Press',
  declineBench: 'Decline Bench Press',
  cableFly: 'Cable fly',
  cablePress: 'Cable Press',
  upperCable: 'Upper Cable Press',
  lowerCable: 'Lower Cable Press',
  bbCurl: 'Barbell Curl',
  ezCrusher: 'EZ Skullcrusher',
  dbCurl: 'Dumbell Curl',
  cablePushDown: 'Cable Push Down',
  revCablePushDown: 'Reverse Cable Push Down',
  cableHammer: 'Cable Hammer Curl',
  pullup: 'Pullup',
  wpullup: 'Weighted Pullup',
  bbRow: 'Barbell bentover Row',
  latpullDown: 'Lat Pull Down',
  cableRow: 'Cable Row',
  backPullDown: 'Straight Arm Bar Pull Down',
  closePullDown: 'Close Grip Pull Down',
  calfRaises: 'Calf Raises',
  SMCalfRaises: 'Smith Machine Calf Raises',
  tricepDips: 'Tricep Dips',
  ezPreacherCurl: 'Ez Prepacher Curl',
  reverseLatPullDown: 'Reverse Lat Pull Down',
  dbRow: 'Dumbell Row',
  tBarRow: 'T-Bar Row',
  bbDeadlift: 'Barbell Deadlift',
  backExtension: 'Back Extension',
  seatedDBLateralRaises: 'Seated DB Lateral Raises',
  standShoulderPress: 'Standing Shoulder Press',
  bbFrontRaises: 'Barbell Front Raises',
  cableLateralRaises: 'Cable Lateral Raises',
  rearDeltFly: 'Rear Delt Fly',
  dbShrug: 'Dumbell Shrugs',
  squats: 'Squates',
  hipThrust: 'Hip Thrust',
  rdl: 'Romainian Deadlift',
  splitSquats: 'Split Squats',
  lunges: 'Lunges',
  dbHipAbduction: 'Dumbell Hip Abduction',
  dbStepUps: 'Dumbell Step Ups',
};
