import {RoutineInfo} from '../models/routines';

export const ROUTINES: RoutineInfo[] = [
  {
    id: '1',
    name: 'Routine 1',
    durationWeeks: 4,
    exercise: {
      'Day 1': [],
      'Day 2': [],
      'Day 3': [],
      'Day 4': [],
      'Day 5': [],
      'Day 6': [],
      'Day 7': [],
      'Day 8': [],
      'Day 9': [],
      'Day 10': [],
      'Day 11': [],
    },
    estTime: '',
  },
  {
    id: '2',
    name: 'Routine 2',
    durationWeeks: 12,
    excercise: [],
    estTime: '',
  },
  {
    id: '3',
    name: 'Routine 3',
    durationWeeks: 6,
    excercise: [],
    estTime: '',
  },
  {
    id: '4',
    name: 'Routine 4',
    durationWeeks: 4,
    excercise: [],
    estTime: '',
  },
  {
    id: '5',
    name: 'Routine 5',
    durationWeeks: 12,
    excercise: [],
    estTime: '',
  },
  {
    id: '6',
    name: 'Routine 6',
    durationWeeks: 6,
    excercise: [],
    estTime: '',
  },
  {
    id: '7',
    name: 'Routine 7',
    durationWeeks: 4,
    excercise: [],
    estTime: '',
  },
  {
    id: '8',
    name: 'Routine 8',
    durationWeeks: 12,
    excercise: [],
    estTime: '',
  },
  {
    id: '9',
    name: 'Routine 9',
    durationWeeks: 6,
    excercise: [],
    estTime: '',
  },
];
